### ISSUE TITLE
Openlayers.Lang wrong loading order

### ISSUE THREAD

**Issue by bierik** [collective/collective.geo.openlayers#3]
We got a randomly ``` ReferenceError: OpenLayers is not defined ``` error when loading the translations for German in openlayers.

The error occurs in this file https://github.com/collective/collective.geo.openlayers/blob/master/src/collective/geo/openlayers/skins/geo_openlayers/lang/de.js

The Openlayers library is loaded here https://github.com/collective/collective.geo.openlayers/blob/master/src/collective/geo/openlayers/profiles/default/jsregistry.xml#L9

The language file is loaded here
https://github.com/collective/collective.geo.mapwidget/blob/master/src/collective/geo/mapwidget/browser/collectivegeo_macros.pt#L26

So my best guess is a fail in the loading order.

The ``` <script> ``` tags get rendered simultaneously.

According to my timeline in Chrome the ``` openlayers.js ``` takes longer to load than the ``` de.js ```
![bildschirmfoto 2015-07-15 um 10 07 42 kopie](https://cloud.githubusercontent.com/assets/1637820/8693785/06e4dd64-2ada-11e5-97d9-f28f3023531f.png)

So an event would be necessary to synchronize the loading order.

What's the best way to fix it?

**Comment by jone** [comment]
:+1: It would be nice having this fixed :wink:

**Comment by bierik** [comment]
Trying to achieve something here seems to be pointless.
