### ISSUE TITLE
2.5 broken: does not show google layer

### ISSUE THREAD

**Issue by rnd0101** [collective/collective.geo.openlayers#5]
OpenLayers 2 has been updated to address problems with Google layers (easily seen when trying all-overlays-google.html / all-overlays-google.js example, where gmap is the first or only layer, and visibility set to true). In short: google maps layer is white unless layer is switched to something else and back.

Is there any chance 2.5 will be updated to the latest 2.13.1 OpenLayers branch?

FYI, this OL2 patch dated December 8 fixes the problem: https://github.com/openlayers/ol2/commit/482e61aad4ba758897524f607f7986ece1655327  (size of commit is deceptive due to whitespace cleaning, the essential change is just in one place)

**Comment by maethu** [comment]
@rnd0101 I released collective.openlayers 3.2b1 (for Plone 4.x), which includes this fix.
